/* BAZA UCZESTNIKÓW — PARP Future Camp 2026, Ryn
   Źródło: intro wrzucone przez ludzi na grupę WhatsApp.
   ZASADA: wchodzi tylko to, co człowiek sam napisał na grupie.
   Numery telefonów widoczne na zrzutach NIE wchodzą do bazy.

   seeks  = POPYT  (czego szuka)   -> matchuje się z offers innych
   offers = PODAŻ  (w czym pomoże) -> matchuje się z seeks innych
   hidden = true   -> nie idzie na stronę                             */

window.PROFILES = [

{ id:"damian-wilinski", name:"Damian Wiliński", company:"Merdilo",
  headline:"Merdilo — apka, która z dźwięku rozpoznaje zachowanie psa",
  url:"https://merdilo.com/", linkedin:"https://www.linkedin.com/in/damianwilinski/",
  does:"Analiza dźwięku w czasie rzeczywistym + AI wykrywające wzorce zachowania psa. Apka na 4 platformach. Z behawiorystami rozwija Merdilo Pro — platformę łączącą obserwacje z domu z pracą specjalisty. Przed pilotażem.",
  seeks:["GTM dla B2B2C","partnerstwa","skalowanie pet-techu","kontakt do behawiorystów i weterynarzy"],
  offers:["wdrażanie AI w produkcie","aplikacje cross-platform","analiza dźwięku / audio ML","dowiezienie produktu do storów"],
  tags:["pettech","ai","mobile","b2b2c","produkt"],
  keywords:"gtm b2b2c partnerstwa pettech ai ml audio dzwiek aplikacja mobilna cross-platform ios android pilotaz" },

{ id:"tomasz-guzik", name:"Tomasz Guzik", company:"FunnelHouse AI",
  headline:"FunnelHouse AI — CRM sterowany głosem, zasilany agentami",
  url:"", linkedin:"",
  does:"Prawie dekada w kampaniach reklamowych i lejkach sprzedażowych, edukuje w tym zakresie. Zbudował workflow startowania projektów od zera do pierwszych transakcji w 48h z AI + własne listy i zasięgi. Wprowadza na rynek FunnelHouse AI — CRM do marketingu, sprzedaży i obsługi klienta w jednym. Duże kampanie live: webinary, autowebinary. Od niedawna eventy stacjonarne w Warszawie.",
  seeks:["startupy z potencjałem, gdzie wdroży swoje procesy","wzrost liczby userów i klientów"],
  offers:["kampanie reklamowe","lejki sprzedażowe","webinary i autowebinary","pierwsze transakcje w 48h","AI w marketingu","agenci i CRM","eventy stacjonarne"],
  tags:["marketing","sprzedaz","ai","crm","saas"],
  keywords:"kampanie reklama lejek funnel webinar autowebinar crm agenci ai marketing sprzedaz konwersja leady event stacjonarny" },

{ id:"roland-ecmr", name:"Roland", company:"e-cmr.com",
  headline:"e-cmr.com — cyfrowy standard listów przewozowych CMR",
  url:"https://e-cmr.com", linkedin:"https://www.linkedin.com/in/logmap/",
  does:"Zastępuje papierowe listy przewozowe CMR w 100% legalnym standardem cyfrowym. Papier generuje straty i zatory płatnicze w transporcie drogowym.",
  seeks:["inwestor smart money","ktoś rozumiejący skalowanie B2B","rynki logistyczne","ekspansja"],
  offers:["transport drogowy i logistyka","cyfryzacja dokumentów","legalność i compliance standardu","sprzedaż B2B do branży transportowej"],
  tags:["logistyka","b2b","saas","finansowanie"],
  keywords:"transport logistyka cmr spedycja dokumenty cyfryzacja compliance inwestor runda skalowanie b2b" },

{ id:"krzysztof-swianiewicz", name:"Krzysiek Świaniewicz", company:"estateapp.pl",
  headline:"PropTech — pozyskiwanie i selekcja leadów nieruchomościowych z AI",
  url:"https://estateapp.pl/", linkedin:"https://www.linkedin.com/in/krzysztof-świaniewicz-3a8355b4/",
  does:"Prawie dekada na rynku nieruchomości. Z zespołem przygotowuje nieruchomości inwestycyjne w Warszawie, równolegle buduje startup PropTech. Kilku płacących klientów, abonament ~1500 zł/mc, zespół 7 osób, bootstrap. Szacowany SOM ~400k MRR.",
  seeks:["kapitał na przyspieszenie","wspólnik","współpracownik","wymiana wiedzy"],
  offers:["rynek nieruchomości","PropTech","generowanie i selekcja leadów z AI","sprzedaż abonamentowa B2B","bootstrapping","budowa zespołu"],
  tags:["proptech","nieruchomosci","ai","b2b","saas"],
  keywords:"nieruchomosci proptech leady lead generation abonament mrr som bootstrap zespol warszawa inwestycje" },

{ id:"krzysztof-kolodziejczyk", name:"Krzysztof Kołodziejczyk", company:"Ambientra",
  headline:"Ambientra — urządzenia Senior Care",
  url:"", linkedin:"https://www.linkedin.com/in/krzysztof-kolodziejczyk-ops",
  does:"Urządzenia do opieki nad seniorami. Potrzebuje warstwy AI do obsługi podopiecznych oraz interfejsu HMI, który osoba starsza obsłuży sama i który będzie codziennym towarzyszem.",
  seeks:["rozwiązanie AI do obsługi podopiecznych","HMI dla osób starszych","UX dla seniorów","partnerzy technologiczni"],
  offers:["hardware dla seniorów","silver economy","urządzenia opiekuńcze","wdrożenia w opiece"],
  tags:["hardware","silver-economy","zdrowie","ai"],
  keywords:"senior care seniorzy opieka urzadzenia hardware hmi interfejs ux ai asystent glosowy" },

{ id:"joanna-returnready", name:"Joanna", company:"ReturnReady",
  headline:"ReturnReady — HR-tech, powrót pracowników po dłuższej przerwie",
  url:"", linkedin:"https://www.linkedin.com/in/joanna-cz",
  does:"Kilkanaście lat w psychologii pracy i transportu, pozwoleniach na broń, psychodietetyce. Od niedawna w IT jako QA i PM, dokumentacja projektowa, współpraca z software housem CetusPro. Buduje ReturnReady na styku reboardingu i HR-tech: bezpieczniejszy powrót pracownika po przerwie, narzędzia dla firm, z poszanowaniem prywatności pracownika.",
  seeks:["feedback do pivotu","wartościowe relacje","wymiana doświadczeń"],
  offers:["QA i testowanie","project management","dokumentacja projektowa","HR-tech","psychologia pracy","konstruktywny feedback","procesy w software house"],
  tags:["hrtech","qa","pm","psychologia"],
  keywords:"hr hrtech reboarding onboarding qa testy pm project manager dokumentacja psychologia pracy software house" },

{ id:"marcin-sowinski", name:"Marcin Sowiński", company:"Sky Bridge",
  headline:"Sky Bridge — drony BVLOS dla Bałtyku, monitoring farm wiatrowych i portów",
  url:"", linkedin:"https://www.linkedin.com/in/marcin-sowinski-358a9433",
  does:"Za dnia offshore wind, po godzinach buduje Sky Bridge — platformę pod drony BVLOS, żeby farmy wiatrowe i porty miały monitoring bez wysyłania ludzi na wodę. Pre-seed, pracuje nad kilkoma LOI od deweloperów i portów, układa zespół.",
  seeks:["techniczny co-founder / CTO","hardware i autonomia","fundusze deep-tech i hardware","szczera krytyka modelu biznesowego"],
  offers:["offshore wind","drony BVLOS","regulacje lotnicze","sprzedaż do deweloperów i portów","pilotaże i LOI w przemyśle"],
  tags:["deeptech","hardware","drony","energia","b2b"],
  keywords:"drony bvlos offshore wind farmy wiatrowe porty morze baltyk deeptech hardware cto cofounder pre-seed loi fundusz" },

{ id:"izabela-glebicka", name:"Izabela Głębicka", company:"NeuroDome by PsycheFuture",
  headline:"NeuroDome — mobilna kopuła, neurotechnologia, pomiar stresu na żywo",
  url:"", linkedin:"https://www.linkedin.com/in/izabela-głębicka/",
  does:"Psycholog, inicjatorka sekcji Psychologii Cyfrowej w Polskim Towarzystwie Psychologicznym, zespół organizacyjny HumanTech 2026 na SWPS. Tworzy NeuroDome — immersyjną kopułę z certyfikowanymi urządzeniami medycznymi, pasywnie regulującą układ nerwowy, z odczytem stresu w czasie rzeczywistym. Technologia gotowa, infrastruktura mobilna z własnym zasilaniem.",
  seeks:["hotele i centra konferencyjne w Warszawie","platformy mental health do integracji","korporacje na pakiety B2B dla pracowników","coachowie i liderzy opinii na prowizję"],
  offers:["neurotechnologia","pomiar stresu i fizjologii","wellbeing na twardych danych","organizacja konferencji","mobilna infrastruktura eventowa","psychologia cyfrowa"],
  tags:["healthtech","wellbeing","hardware","b2b","event"],
  keywords:"neurotechnologia stres wellbeing kopula neurodome urzadzenia medyczne hotele konferencje korporacje b2b prowizja psychologia" },

{ id:"kamil-jablonski", name:"Kamil Jabłoński", company:"",
  headline:"Księgowość dla startupów",
  url:"https://tidycal.com/kamiljablonski/parp-future-camp-talks", linkedin:"https://www.linkedin.com/in/kjablonsk",
  does:"Chce słuchać o bolączkach księgowych founderów. Wprost nie mówi, dlaczego go to interesuje, żeby nie łamać zasady o kryptoreklamie. Ma zaplecze 0→1 i dzieli się doświadczeniem. Otwarty kalendarz na 15-minutowe rozmowy przed eventem.",
  seeks:["rozmowy o bolączkach księgowych founderów"],
  offers:["księgowość i rozliczenia w startupie","budowanie 0→1","rozmowa 1:1 przed eventem"],
  tags:["ksiegowosc","finanse","operacje"],
  keywords:"ksiegowosc rachunkowosc podatki rozliczenia spolka faktury finanse startup 0-1" },

{ id:"adriana-sidor", name:"Adriana Sidor", company:"Blindly",
  headline:"Blindly — startup na inkubacji; własna firma IT robiąca UX/UI i development",
  url:"", linkedin:"https://www.linkedin.com/in/adriana-sidor-133329187",
  does:"Startup Blindly na inkubacji w Startin, pierwszy etap, 90k na start. Na co dzień prowadzi własną firmę IT — robią cały UX/UI i programowanie.",
  seeks:["rozmowy z ludźmi na drodze startupowej"],
  offers:["UX/UI","programowanie","budowa produktu na zlecenie","przejście przez inkubację","pierwsze finansowanie"],
  tags:["it","ux","development","inkubacja"],
  keywords:"ux ui design programowanie development firma it software house inkubacja startin dotacja 90k mvp" },

{ id:"tomasz-bill", name:"Tomasz Bill", company:"",
  headline:"— brak opisu, czeka na nagłówek z LinkedIna",
  url:"", linkedin:"https://www.linkedin.com/in/tomaszbill",
  does:"Nie napisał, czym się zajmuje. Będzie od poniedziałku do wtorku popołudnia. Biegania nie lubi, proponuje rolki, trening albo dłuższy spacer.",
  seeks:[], offers:[], tags:[], keywords:"", incomplete:true },

{ id:"mateusz-winiarek", name:"Mateusz Winiarek", company:"",
  headline:"Lean, optymalizacja procesów, wątki AI",
  url:"", linkedin:"https://www.linkedin.com/in/mateusz-winiarek-8937351",
  does:"Tematy leanowe, optymalizacyjne i procesowe z wątkami AI. Na miejscu od poniedziałku od samego rana.",
  seeks:["rozmowy o lean, optymalizacji i procesach"],
  offers:["lean","optymalizacja procesów","procesy z AI","usprawnianie operacji"],
  tags:["lean","procesy","ai","operacje"],
  keywords:"lean kaizen optymalizacja proces procesy operacje efektywnosc automatyzacja ai wdrozenie" },

{ id:"agnieszka-kakol", name:"Agnieszka Kąkol", company:"Flowstaff",
  headline:"Flowstaff — HRTech / EventTech, gotowy produkt, akceleracja w Dolinie Krzemowej",
  url:"https://flowstaff.eu", linkedin:"https://www.linkedin.com/in/agnieszkakakol",
  does:"Founderka i CEO Flowstaff. Budowała operacyjnie biznes przez 8 lat, od dwóch przekłada to na startup. Realizują komponent 2a oraz booster, plus finansują startup z operacyjnej działalności. Produkt gotowy. W październiku lecą do Doliny Krzemowej na kontynuację akceleracji w programie USA NCBR jako 1 z 10 firm z Polski. Mieszka w Rzeszowie.",
  seeks:["rozmowy o wyzwaniach","kontakty pod ekspansję USA","exit"],
  offers:["HRTech i EventTech","budowanie biznesu operacyjnego","finansowanie startupu z własnej działalności","programy akceleracyjne NCBR","wejście na rynek USA"],
  tags:["hrtech","eventtech","saas","usa","akceleracja"],
  keywords:"hrtech eventtech pracownicy eventy akceleracja ncbr dolina krzemowa usa ekspansja bootstrapping exit rzeszow" },

{ id:"agata-bendik", name:"Agata Bendik", company:"",
  headline:"Zdrowie kobiet; wcześniej długo w UK i Danii",
  url:"", linkedin:"https://www.linkedin.com/in/agatamariabendik",
  does:"Po długim czasie w UK i Danii wróciła do Polski. Pracuje w świecie zdrowia kobiet. Z Kaszub.",
  seeks:["osoby zainteresowane tematem zdrowia kobiet","nowe znajomości"],
  offers:["zdrowie kobiet","doświadczenie z rynków UK i Danii"],
  tags:["healthtech","femtech","zagranica"],
  keywords:"zdrowie kobiet femtech uk dania zagranica rynki miedzynarodowe kaszuby", thin:true },

{ id:"marino-papazachariou", name:"Marino Papazachariou", company:"Ask to Sell",
  headline:"Ask to Sell — agencja rozwoju sprzedaży B2B; 25 lat w sprzedaży",
  url:"", linkedin:"",
  does:"25 lat w sprzedaży: bankowość i finanse, zarządzanie zespołami, własne firmy. Ma udziały w spółkach związanych z medycyną. Prowadzi Ask to Sell — pozyskują leady, układają procesy, trenują handlowców w firmach B2B. Równolegle uczy firmy korzystać z AI (Akademia AI dla Biznesu) i buduje narzędzia robiące robotę za handlowca.",
  seeks:["ludzie, którzy robią, a nie tylko planują","dobre pytania","poznanie projektów innych"],
  offers:["sprzedaż B2B","pozyskiwanie leadów","układanie procesu sprzedaży","szkolenie handlowców","AI dla biznesu","narzędzia automatyzujące pracę handlowca","bankowość i finanse","sektor medyczny"],
  tags:["sprzedaz","b2b","ai","szkolenia","finanse"],
  keywords:"sprzedaz handlowcy leady proces sprzedazy trening szkolenie b2b bankowosc finanse medycyna ai automatyzacja agencja" },

{ id:"szymon-romanek", name:"Szymon Romanek", company:"",
  headline:"Dron edukacyjny — sprzęt, aplikacje i materiały do nauki budowy i programowania dronów",
  url:"", linkedin:"https://www.linkedin.com/in/szymon-romanek/",
  does:"Robi dron edukacyjny: sprzęt, aplikacje i materiały dydaktyczne do nauki budowy, pilotażu i programowania dronów.",
  seeks:["rozmowy o edukacji","budowanie hardware","osoby zainteresowane tematem"],
  offers:["edtech","hardware i elektronika","drony","materiały dydaktyczne","produkcja sprzętu"],
  tags:["edtech","hardware","drony","edukacja"],
  keywords:"drony edukacja edtech hardware elektronika produkcja szkola nauka programowanie materialy dydaktyczne" },

{ id:"bartosz-swiatowski", name:"Bartosz Światowski", company:"Ticho.app",
  headline:"Campboxy — zabudowy kempingowe; Ticho.app — ciche miejscówki dla podróżników",
  url:"https://ticho.app", linkedin:"https://www.linkedin.com/in/bartosz-swiatowski",
  does:"Rzemieślnik, buduje rzeczy fizyczne i cyfrowe: zabudowy kempingowe Campboxy oraz aplikację Ticho.app ze zweryfikowanymi, cichymi miejscówkami dla podróżników. Na camp przyjedzie własnym mini kamperem z zabudową.",
  seeks:["walidacja projektów","poznanie, co budują inni"],
  offers:["produkcja i rzemiosło","zabudowy kempingowe","budowa produktu fizycznego i cyfrowego","marketplace / aplikacja podróżnicza","walidacja pomysłu"],
  tags:["hardware","produkcja","travel","marketplace"],
  keywords:"kamper camping zabudowa rzemioslo produkcja fizyczny produkt aplikacja marketplace podroze turystyka walidacja" },

{ id:"krzysztof-blaszkiewicz", name:"Krzysztof Błaszkiewicz", company:"BluHolding",
  headline:"IT, cyberbezpieczeństwo i sektor obronny; Dual-Use, NIS2/KSC",
  url:"", linkedin:"",
  does:"Z Bydgoszczy. Od lat rozwija projekty technologiczne na styku IT, cyberbezpieczeństwa i sektora obronnego. Współpracuje z wojskiem, branżą zbrojeniową i służbami mundurowymi: rozwiązania Dual-Use, compliance NIS2/KSC, zabezpieczenia infrastruktury krytycznej UoKSC. Rada Rozwoju Gospodarczego Województwa Kujawsko-Pomorskiego, Prezes Zarządu BluHolding.",
  seeks:["projekty B2B mierzące się z cyberbezpieczeństwem","technologie o potencjale Dual-Use"],
  offers:["cyberbezpieczeństwo","compliance NIS2/KSC","infrastruktura krytyczna","wejście na rynek wojskowy","przetargi dla służb","Dual-Use","skalowanie sprzedaży B2B","kontakty w sektorze obronnym"],
  tags:["cybersec","defence","b2b","compliance"],
  keywords:"cyberbezpieczenstwo cybersec nis2 ksc uoksc infrastruktura krytyczna wojsko obronny defence dual-use przetarg sluzby mundurowe compliance b2b" },

{ id:"hubert-lechowicz", name:"Hubert Lechowicz", company:"",
  headline:"Big Data i AI; platforma „technolog fermentacji w smartfonie”",
  url:"", linkedin:"https://www.linkedin.com/in/hubert-lechowicz-97035a16b",
  does:"Robi w Big Data i AI. Rozwija własny projekt: platforma dla producentów napojów fermentowanych — technolog fermentacji w smartfonie. Wspiera go kilka osób w ramach Laboratorium Innowatora oraz know-how z rodzinnej sodowni rzemieślniczej. Plan wypuszczenia MVP na koniec roku. Ze Śląska.",
  seeks:["wymiana doświadczeń","rozmowy o tematach data-related"],
  offers:["Big Data","AI i modele na danych","tematy data-related","produkcja napojów i fermentacja","budowa MVP"],
  tags:["ai","data","foodtech","mvp"],
  keywords:"big data dane analityka ai model fermentacja napoje browar sodownia produkcja mvp laboratorium innowatora slask" },

{ id:"radek-furmanek", name:"Radek Furmanek", company:"4Soul Media / TRIPUJ",
  headline:"Operator kamery i reżyser; founder TRIPUJ — nowa fala turystyki",
  url:"", linkedin:"",
  does:"Główna branża: operator kamery i reżyser, formy dokumentalne, wideoklipy, reklamy. Robił content wideo dla Samsung, Black, 4Move, Prosto, Open'er i wielu innych. Ostatnio coraz więcej pracy przy socialach dla mniejszych marek. Founder startupu TRIPUJ — nowa fala turystyki, launch do końca roku, gotowe MVP.",
  seeks:["walidacja założeń projektu turystycznego","partnerzy do realizacji","osoby zainteresowane turystyką doświadczeń"],
  offers:["produkcja wideo i reklamy","formy dokumentalne","content na social media","współpraca z dużymi markami","turystyka doświadczeń"],
  tags:["media","video","travel","marketing"],
  keywords:"wideo video film reklama dokument klip operator rezyser content social media marka turystyka podroze tripuj mvp" },

{ id:"artur-pososhko", name:"Artur Pososhko", company:"",
  headline:"Automatyzacje procesów na n8n; Data, Automation & AI w Kyriba",
  url:"", linkedin:"https://www.linkedin.com/in/artur-pososhko",
  does:"Z Warszawy. Buduje automatyzacje procesów na n8n, na co dzień w zespole Data, Automation & AI w Kyriba. Wcześniej 5 lat w affiliate marketingu, gdzie oprócz klientów ogarniał automatyzacje dla zespołu.",
  seeks:["poznanie, co budują inni"],
  offers:["automatyzacja procesów","n8n","integracje","data i AI w firmie","affiliate marketing","ocena czy coś warto automatyzować"],
  tags:["automatyzacja","nocode","ai","data","marketing"],
  keywords:"automatyzacja n8n nocode no-code workflow integracje api data ai affiliate marketing procesy recznie" },

{ id:"anastazja-surynava", name:"Anastazja Surynava", company:"ESSA.app",
  headline:"ESSA.app — HRTech, mobilna platforma AI: Job Match i rozwój kompetencji",
  url:"https://essa.app", linkedin:"https://www.linkedin.com/in/asurynava",
  does:"Founderka ESSA.app — polskiego startupu HRTech budującego mobilną platformę AI, która łączy Job Match, rozwój kompetencji i przygotowanie do rekrutacji w jednym ekosystemie. Model B2C, w przyszłym roku wejście w B2B i ekspansja międzynarodowa. W pierwszym roku platforma przekroczyła 100 tys. użytkowników. Top 15 HR Tech companies and startups in Poland, luty 2026.",
  seeks:["osoby z doświadczeniem wyjścia do B2B w USA","aniołowie biznesu","VC"],
  offers:["HRTech","rekrutacja i kompetencje","skalowanie B2C do 100 tys. userów","budowa platformy mobilnej AI","wzrost konsumencki"],
  tags:["hrtech","ai","mobile","b2c","usa"],
  keywords:"hrtech rekrutacja praca job match kompetencje ai aplikacja mobilna b2c uzytkownicy wzrost usa ekspansja aniol vc runda" },

{ id:"staszek-brightmind", name:"Staszek", company:"BrightMind",
  headline:"BrightMind — narzędzie dla osób z ADHD",
  url:"https://brightmind.club", linkedin:"https://www.linkedin.com/in/szelemeh/",
  does:"Buduje BrightMind — opisuje to jako „OpenClaw dla osób z ADHD”.",
  seeks:[], offers:["budowa narzędzia konsumenckiego","produkty wspierające koncentrację i organizację pracy"],
  tags:["produkt","ai","b2c"],
  keywords:"brightmind adhd narzedzie asystent koncentracja organizacja pracy produkt konsumencki", thin:true },

{ id:"angelo-korzekwa", name:"Angelo Korzekwa", company:"",
  headline:"6 lat przy RocketJobs i Just Join IT; projekt mentoringowy dla innowatorów społecznych",
  url:"", linkedin:"https://www.linkedin.com/in/angelokorzekwa",
  does:"Przez 6 lat współtworzył RocketJobs i Just Join IT. Teraz rozwija projekt mentoringowy dla innowatorów społecznych — celem jest awans Polski do 2035 roku w World Happiness Report.",
  seeks:["rozmowy o sprzedaży, HR, żeglarstwie i psychologii"],
  offers:["budowanie marketplace'u pracy od zera","sprzedaż","HR","mentoring","projekty impactowe","psychologia w biznesie"],
  tags:["hr","sprzedaz","impact","marketplace"],
  keywords:"rocketjobs justjoinit marketplace praca rekrutacja sprzedaz hr mentoring impact spoleczny psychologia zeglarstwo" },

{ id:"marcel-olbryt", name:"Marcel Olbryt", company:"Avaloq",
  headline:"Szwajcarski fintech, obszar bankowości; finanse i rynki kapitałowe",
  url:"", linkedin:"https://www.linkedin.com/in/marcel-olbryt-a31085280",
  does:"23 lata, pracuje w szwajcarskim fintechu Avaloq w obszarze bankowości. Skończył International Business na UE Wrocław, od października podyplomowe investment banking na SGH. Zawodowo i prywatnie mocno interesuje się finansami, inwestowaniem i rynkami kapitałowymi.",
  seeks:["rozmowy o finansach, inwestowaniu i rynkach kapitałowych"],
  offers:["fintech i bankowość","rynki kapitałowe","inwestowanie","perspektywa rynku szwajcarskiego"],
  tags:["fintech","finanse","bankowosc"],
  keywords:"fintech bankowosc bank finanse inwestowanie rynki kapitalowe investment banking szwajcaria avaloq" },

{ id:"michal-voldeno", name:"Michał", company:"Voldeno",
  headline:"Voldeno — polski system automatyki budynkowej z własnym językiem programowania",
  url:"https://voldeno.com", linkedin:"",
  does:"Z Łodzi. Współzałożyciel Voldeno — systemu automatyki budynkowej łączącego prostotę z brakiem ograniczeń. Własny język programowania i runtime, logikę budynku można komponować z pomocą AI zamiast żmudnej konfiguracji. Wszystko in-house, bez zewnętrznego finansowania: od elektroniki produkowanej na własnej linii SMT po oprogramowanie i aplikację mobilną. 5 modułów gotowych do sprzedaży, 2 w prototypach, pierwsze wdrożenia komercyjne. Rynek zdobywa przez instalatorów smart home. Zawodowo architekt rozwiązań w obszarze danych i chmury.",
  seeks:["rozmowy o rozwoju produktu i rynku"],
  offers:["automatyka budynkowa i smart home","produkcja elektroniki, własna linia SMT","projektowanie języka programowania i runtime","architektura danych i chmury","sprzedaż przez kanał instalatorów","budowa hardware bez finansowania zewnętrznego"],
  tags:["hardware","iot","smarthome","deeptech","produkcja"],
  keywords:"automatyka budynkowa smart home iot elektronika smt produkcja hardware jezyk programowania runtime chmura dane architekt instalatorzy kanal sprzedazy" },

{ id:"krystian-g2m", name:"Krystian", company:"",
  headline:"Strategie Go-To-Market dla startupów; wydał ok. 4 mln zł na testowanie kanałów",
  url:"", linkedin:"",
  does:"Zaprasza na osobne spotkania o strategiach Go-To-Market dla startupów. Osobiście wydał ok. 4 mln zł na różne strategie G2M. Chce dzielić się doświadczeniami: outbound, inbound, SEM, influencerzy, cold outreach (LinkedIn, mail), budowa baz, eventy, AI. Prowadzi społeczność WhatsApp G2M.",
  seeks:["osoby, które podzielą się doświadczeniami z G2M"],
  offers:["strategie Go-To-Market","outbound i cold outreach","inbound","SEM","influencer marketing","budowa baz kontaktów","eventy jako kanał","AI w sprzedaży"],
  tags:["gtm","marketing","sprzedaz","b2b"],
  keywords:"gtm g2m go-to-market outbound inbound sem influencer cold mail linkedin bazy kontaktow eventy kanaly sprzedaz startup" },

{ id:"natalia-siewiera", name:"Natalia Siewiera", company:"marsistant",
  headline:"marsistant — marketing dla firm, które mają mało pieniędzy, czasu lub ludzi",
  url:"https://marsistant.com/pl/", linkedin:"https://www.linkedin.com/in/nataliasiewiera/",
  does:"Marketing. Specjalizuje się w wyzwaniach, gdzie na marketing jest mało pieniędzy, czasu i/lub ludzi. Pomaga indywidualnie i zespołowo, współtworzyła marsistant — narzędzie do ogarniania marketingu dopasowane do firmy.",
  seeks:["rozmowy o wyzwaniach marketingowych"],
  offers:["marketing przy małym budżecie","marketing bez zespołu","strategia marketingowa","narzędzia marketingowe","doradztwo marketingowe"],
  tags:["marketing","narzedzia","doradztwo"],
  keywords:"marketing budzet maly zespol strategia kampania narzedzie marsistant doradztwo promocja" },

{ id:"kamila-maliszewska", name:"Kamila Maliszewska", company:"",
  headline:"BHP + trenerka mentalna; buduje e-learningi łączące BHP z tematyką stresu i wypalenia",
  url:"", linkedin:"https://www.linkedin.com/in/kamila-maliszewska",
  does:"Specjalistka BHP i trenerka mentalna. Chce stworzyć e-learningi łączące obowiązkowe BHP i pierwszą pomoc z tematyką stresu, przeciążenia, wypalenia i innych zagrożeń psychospołecznych w pracy. Szkolenia z interakcją, scenariuszami, symulacjami realnych sytuacji i elementami psychologii — nie przeklikiwanie slajdów. W prowadzeniu własnego biznesu początkująca.",
  seeks:["osoby od e-learningu","AI","tworzenie produktów cyfrowych","marketing","skalowanie","finansowanie","weryfikacja pomysłu"],
  offers:["BHP i pierwsza pomoc","szkolenia i trening mentalny","tematyka zagrożeń psychospołecznych w pracy","projektowanie szkoleń"],
  tags:["edtech","szkolenia","hr","bhp"],
  keywords:"bhp szkolenia elearning e-learning kurs pierwsza pomoc stres wypalenie psychospoleczne trener mentalny produkt cyfrowy skalowanie finansowanie" },

{ id:"adam-wierchola", name:"Adam Wierchoła", company:"prorok.systems",
  headline:"prorok.systems — agentowe AI + modelowanie i symulacja do planowania i risk managementu",
  url:"https://prorok.systems", linkedin:"https://www.linkedin.com/in/adam-wierchola/",
  does:"Spod Warszawy, doświadczony software engineer. Rozwija prorok.systems — startup łączący agentowe AI z technikami modelowania i symulacji, pod zaawansowane rozwiązania planistyczne, decision intelligence i risk management.",
  seeks:["osoby, którym rezonują tematy planowania, symulacji i risk managementu"],
  offers:["agentowe AI","modelowanie i symulacja","decision intelligence","risk management","inżynieria oprogramowania"],
  tags:["ai","b2b","deeptech","software"],
  keywords:"agenci ai agentowe symulacja modelowanie planowanie planistyczne decision intelligence risk management ryzyko optymalizacja software engineer" },

{ id:"rafal-kaszubski", name:"Rafał Kaszubski", company:"Free to Dream",
  headline:"Free to Dream — społeczność akademii sportowych, wdrożenia AI i pozyskiwanie środków",
  url:"", linkedin:"https://www.linkedin.com/in/rafal-kaszubski-bizedusport/",
  does:"Z Lublina, misja: zmieniać świat przez sport. Od kilku miesięcy rozwija Free to Dream — buduje społeczność akademii sportowych stawiających na nowoczesny rozwój. Pomagają wdrażać do akademii AI, pozyskiwać środki, lepiej zarządzać i zarabiać, a młodym zawodnikom dawać lepsze perspektywy. Model łączący biznes i NGO.",
  seeks:["partnerzy do rozwoju projektu sportowego"],
  offers:["sport i akademie sportowe","wdrażanie AI w organizacjach","pozyskiwanie środków i grantów","model łączący biznes z NGO","budowanie społeczności"],
  tags:["sport","impact","ngo","ai","edukacja"],
  keywords:"sport akademia sportowa mlodziez trener ngo fundacja granty srodki dotacje ai wdrozenie spolecznosc lublin" },

{ id:"klaudia-wez-to-nagraj", name:"Klaudia", company:"Wez To Nagraj",
  headline:"Social media i widoczność marki — warsztaty, szkolenia, konsultacje",
  url:"", linkedin:"https://www.linkedin.com/in/klaudia-m74a4962447",
  does:"Z Trójmiasta. Pomaga firmom rozwijać się w internecie przez warsztaty, szkolenia i konsultacje — zwiększa sprzedaż i rozpoznawalność marki działaniami w social media. Współorganizatorka konferencji dla kobiet „Nie na później” (dwie edycje), laureatka konkursu Tytani Przedsiębiorczości. Prywatnie prowadzi projekt Karmię Kreatywność — przez 40 dni uczy się nowych rzeczy i publikuje to na YouTube.",
  seeks:["ktoś, kto nauczy ją czegoś nowego","nowe znajomości"],
  offers:["social media","budowanie rozpoznawalności marki","warsztaty i szkolenia","content na YouTube","organizacja konferencji"],
  tags:["marketing","social","szkolenia","event"],
  keywords:"social media instagram youtube content marka rozpoznawalnosc sprzedaz warsztaty szkolenia konsultacje konferencja trojmiasto" },

{ id:"natasza-beck-kuzelewska", name:"Natasza Beck-Kuźelewska", company:"",
  headline:"EdTech — startup analizujący luki edukacyjne uczniów, po boosterze, wdrożenia w szkołach",
  url:"", linkedin:"",
  does:"Z Warszawy. Studiowała filozofię, potem informatykę, uczyła matematyki, założyła startup do analizy luk edukacyjnych uczniów. Po jednym boosterze, weszli już do szkół, teraz szykują się na większe wdrożenia. Misja: żeby uczniowie wreszcie dowiedzieli się, czego nie wiedzą. Świadoma, że EdTech bywa trigger warningiem u VC.",
  seeks:["inwestor","budowanie trakcji","VC, który nie odbija się od EdTechu"],
  offers:["EdTech","wdrożenia w szkołach","dydaktyka i matematyka","analiza danych edukacyjnych","sprzedaż do sektora edukacji"],
  tags:["edtech","edukacja","b2b","finansowanie"],
  keywords:"edtech edukacja szkola uczniowie nauczyciele matematyka luki wiedzy wdrozenie inwestor vc runda trakcja brainly" },

{ id:"bernard-wroblewski", name:"Bernard Wróblewski", company:"SPARROWS AI",
  headline:"SPARROWS AI — human-centered AI w edukacji; finansowanie z funduszy UE",
  url:"", linkedin:"https://www.linkedin.com/in/bernardwroblewski/",
  does:"Z Otwocka. Wspólnie z Anną rozwija rodzinny startup SPARROWS AI — łączą technologię, edukację i naukę, tworzą rozwiązania wspierające ludzi w uczeniu się, podejmowaniu decyzji i bezpiecznym korzystaniu z technologii. Pracują nad AI Tutorem, ClickGuardem i SIMPATIENT. Równolegle zajmuje się budowaniem i finansowaniem innowacyjnych przedsięwzięć, szczególnie z funduszy UE — od pomysłu i modelu projektu po strategię pozyskania finansowania.",
  seeks:["osoby, które budują, testują i skalują","szczere rozmowy o tym, co jeszcze nie ma gotowej odpowiedzi"],
  offers:["finansowanie z funduszy UE","pisanie i modelowanie projektów dotacyjnych","strategia pozyskania finansowania","human-centered AI","AI w edukacji"],
  tags:["ai","edtech","dotacje","finansowanie"],
  keywords:"fundusze ue dotacje granty ncbr parp wniosek projekt finansowanie ai tutor edukacja human-centered bezpieczenstwo technologii" },

{ id:"hubert-galimski", name:"Hubert Galimski", company:"FerraFlow",
  headline:"FerraFlow — platforma decyzyjna dla producentów konstrukcji stalowych; backend dev w banku",
  url:"", linkedin:"https://www.linkedin.com/in/hubertgalimski/",
  does:"W ciągu dnia programista (Backend Developer w Raiffeisen Bank International AG), po godzinach founder FerraFlow — platformy pomagającej firmom produkującym konstrukcje stalowe podejmować właściwe decyzje. Od 4 miesięcy w inkubatorze Startupolis. W ciągu kilkudziesięciu dni podejście do rozwijania produktu zmieniło mu się o 180 stopni.",
  seeks:["wszystko wokół marketingu i sprzedaży","ciekawi ludzie — niedługo powiększa załogę","nauka rozmawiania z inwestorami"],
  offers:["backend i inżynieria oprogramowania","przemysł i produkcja konstrukcji stalowych","doświadczenia z inkubatora","budowa produktu B2B po godzinach"],
  tags:["b2b","przemysl","software","inkubacja"],
  keywords:"backend programista software konstrukcje stalowe przemysl produkcja decyzje platforma inkubator startupolis marketing sprzedaz inwestorzy rekrutacja" },

{ id:"andrzej-szczepaniak", name:"Andrzej Szczepaniak", company:"",
  headline:"30 lat w korporacjach: zarządzanie, transformacje, Agile, ESG. Dziś własne projekty na styku AI",
  url:"", linkedin:"https://www.linkedin.com/in/szczepaniak-andrzej/",
  does:"Prawie 30 lat pracy w międzynarodowych korporacjach: zarządzanie ludźmi, projektami i transformacjami biznesowymi. Pracował tam, gdzie strategia, technologia, procesy i ludzie muszą działać razem. Kompetencje potwierdzone certyfikatami z zarządzania, Agile, ESG i transformacji. Dziś rozwija własne projekty startupowe, przede wszystkim na styku AI, transformacji organizacji, podejmowania decyzji i nowych modeli pracy.",
  seeks:["sprawdzenie, co da się zbudować poza korporacyjnym światem","wyjście z doświadczenia korporacyjnego w startupy"],
  offers:["zarządzanie i transformacje organizacji","Agile","ESG","zarządzanie projektami","strategia","AI w organizacji","perspektywa korporacyjnego klienta"],
  tags:["zarzadzanie","ai","esg","korporacje","transformacja"],
  keywords:"zarzadzanie projekt transformacja agile esg strategia procesy korporacja enterprise decyzje modele pracy ai" },

{ id:"dominika-chabiniak", name:"Dominika Chabiniak", company:"MWAI",
  headline:"MWAI — inteligentna garderoba online; na co dzień głowa marketingu",
  url:"", linkedin:"https://www.linkedin.com/in/dominika-chabiniak-684181178",
  does:"Na co dzień głowa marketingu, po godzinach rozwija MWAI — inteligentną garderobę online. Produkt na etapie rozwoju.",
  seeks:["osoby po pierwszych rundach finansowania","branża e-commerce","fashion","AI","skalowanie produktów"],
  offers:["marketing","prowadzenie zespołu marketingowego","fashion tech","budowa produktu konsumenckiego po godzinach"],
  tags:["marketing","fashion","ecommerce","ai","b2c"],
  keywords:"marketing ecommerce e-commerce fashion moda garderoba ai produkt konsumencki skalowanie runda finansowanie" },

{ id:"bartosz-chemia", name:"Bartosz", company:"",
  headline:"Chemik na styku chemii i ML; oprogramowanie chemiczne dla Big Pharma",
  url:"", linkedin:"",
  does:"Chemik — synteza organiczna, chemia analityczna, supramolekularna, materiałowa. W trakcie doktoratu pomagał rozwijać platformę do automatyzacji syntezy organicznej, skomercjalizowaną w spinoucie Chemify (>$100m w kolejnych rundach). Później pomost między chemią a ML w polskim startupie molecule.one, ostatnio promującym się współpracą z OpenAI. Aktualnie tworzy oprogramowanie chemiczne dla Big Pharma. Chciał założyć własny zespół akademicki, zrezygnował; myśli o firmie na pograniczu chemii i technologii.",
  seeks:["wspólnicy do firmy na pograniczu chemii i technologii","ujście dla potrzeb badawczych"],
  offers:["chemia i synteza organiczna","ML w chemii","automatyzacja laboratorium","oprogramowanie naukowe","doświadczenie ze spinoutu wartego >$100m","współpraca z Big Pharma"],
  tags:["deeptech","chemia","ai","pharma","nauka"],
  keywords:"chemia synteza organiczna laboratorium automatyzacja ml machine learning molekuly leki pharma spinout komercjalizacja nauka doktorat" },

/* WSTRZYMANE — opis pochodzi z LinkedIna, nie z intro na grupie.
   Nie publikować, dopóki nie napisze czegoś sama. */
{ id:"natalia-herrise", name:"Natalia", company:"HerRise", hidden:true,
  headline:"HerRise — aplikacja wsparcia dla kobiet; społeczność 40 000+",
  url:"", linkedin:"https://www.linkedin.com/in/natalisam",
  does:"Zbudowała największą w Polsce społeczność wsparcia kobiet online (40 000+). Tworzy HerRise — aplikację mobilną ze spersonalizowanym wsparciem. TOP 25 FemTech w Polsce, finalistka Kursory Roku 2025, TEDx Women Toruń, publikacje w Onet i Vogue Polska. 15+ lat w międzynarodowych korporacjach i startupach za granicą.",
  seeks:["rozmowy o współpracy"],
  offers:["budowanie społeczności online do 40 tys. osób","FemTech","aplikacje mobilne","PR i dotarcie do dużych mediów","wystąpienia publiczne","marketing oparty na społeczności"],
  tags:["femtech","spolecznosc","mobile","pr"],
  keywords:"femtech spolecznosc community kobiety aplikacja mobilna pr media tedx wystapienia marketing" },

];
